import type { BookingWithRelations } from "@/types/booking";

const today = new Date();
const fmt = (d: Date) => d.toISOString();
const daysAgo = (n: number, h = 0, m = 0) => {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  d.setHours(h, m, 0, 0);
  return d;
};
const daysAhead = (n: number, h = 0, m = 0) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  d.setHours(h, m, 0, 0);
  return d;
};

export const FAKE_BOOKINGS: BookingWithRelations[] = [
  // Aujourd'hui
  {
    id: "clx1a",
    clientName: "Jean Dupont",
    clientPhone: "+33 6 12 34 56 78",
    pickupAddress: "10 rue de la Paix, Paris",
    dropAddress: "Aéroport CDG, Terminal 2",
    type: "IMMEDIATE",
    scheduledAt: null,
    status: "ACCEPTED",
    telegramMsgId: null,
    notes: null,
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(0, 8, 0)),
    operator: { name: "Marie Opératrice" },
    acceptance: {
      driver: { name: "Karim Benali", phone: "+33 6 98 76 54 32" },
      acceptedAt: fmt(daysAgo(0, 8, 5)),
      etaMinutes: null,
      etaUpdatedAt: null,
      notifiedAt: null,
    },
  },
  {
    id: "clx2b",
    clientName: "Sophie Martin",
    clientPhone: "+33 7 23 45 67 89",
    pickupAddress: "Gare de Lyon, Paris",
    dropAddress: "15 avenue Victor Hugo, Versailles",
    type: "SCHEDULED",
    scheduledAt: fmt(daysAhead(0, 14, 30)),
    status: "PENDING",
    telegramMsgId: null,
    notes: "Client en fauteuil roulant",
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(0, 9, 15)),
    operator: { name: "Marie Opératrice" },
    acceptance: null,
  },
  {
    id: "clx3c",
    clientName: "Ahmed Kader",
    clientPhone: "+33 6 55 44 33 22",
    pickupAddress: "Hôtel Ritz, Place Vendôme",
    dropAddress: "Orly Terminal 4",
    type: "IMMEDIATE",
    scheduledAt: null,
    status: "IN_PROGRESS",
    telegramMsgId: null,
    notes: null,
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(0, 10, 0)),
    operator: { name: "Marie Opératrice" },
    acceptance: {
      driver: { name: "Luc Moreau", phone: "+33 6 11 22 33 44" },
      acceptedAt: fmt(daysAgo(0, 10, 3)),
      etaMinutes: null,
      etaUpdatedAt: null,
      notifiedAt: null,
    },
  },
  {
    id: "clx4d",
    clientName: "Claire Petit",
    clientPhone: "+33 6 77 88 99 00",
    pickupAddress: "Musée du Louvre",
    dropAddress: "Tour Eiffel",
    type: "IMMEDIATE",
    scheduledAt: null,
    status: "COMPLETED",
    telegramMsgId: null,
    notes: "Groupe de 3 personnes",
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(0, 11, 30)),
    operator: { name: "Marie Opératrice" },
    acceptance: {
      driver: { name: "Karim Benali", phone: "+33 6 98 76 54 32" },
      acceptedAt: fmt(daysAgo(0, 11, 35)),
      etaMinutes: null,
      etaUpdatedAt: null,
      notifiedAt: null,
    },
  },
  {
    id: "clx5e",
    clientName: "Paul Dubois",
    clientPhone: "+33 6 00 11 22 33",
    pickupAddress: "Châtelet-Les Halles",
    dropAddress: "La Défense, Tour First",
    type: "IMMEDIATE",
    scheduledAt: null,
    status: "CANCELLED",
    telegramMsgId: null,
    notes: "Annulé par le client",
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(0, 13, 0)),
    operator: { name: "Marie Opératrice" },
    acceptance: null,
  },
  // Hier
  {
    id: "clx6f",
    clientName: "Isabelle Renard",
    clientPhone: "+33 6 44 55 66 77",
    pickupAddress: "Gare Montparnasse",
    dropAddress: "Aéroport CDG Terminal 1",
    type: "IMMEDIATE",
    scheduledAt: null,
    status: "COMPLETED",
    telegramMsgId: null,
    notes: null,
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(1, 7, 0)),
    operator: { name: "Marie Opératrice" },
    acceptance: {
      driver: { name: "Luc Moreau", phone: "+33 6 11 22 33 44" },
      acceptedAt: fmt(daysAgo(1, 7, 10)),
      etaMinutes: null,
      etaUpdatedAt: null,
      notifiedAt: null,
    },
  },
  {
    id: "clx7g",
    clientName: "Marc Leroy",
    clientPhone: "+33 6 33 22 11 00",
    pickupAddress: "Opéra Garnier",
    dropAddress: "Boulogne-Billancourt centre",
    type: "SCHEDULED",
    scheduledAt: fmt(daysAgo(1, 15, 0)),
    status: "COMPLETED",
    telegramMsgId: null,
    notes: null,
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(1, 9, 0)),
    operator: { name: "Marie Opératrice" },
    acceptance: {
      driver: { name: "Karim Benali", phone: "+33 6 98 76 54 32" },
      acceptedAt: fmt(daysAgo(1, 9, 5)),
      etaMinutes: null,
      etaUpdatedAt: null,
      notifiedAt: null,
    },
  },
  // Il y a 2 jours
  {
    id: "clx8h",
    clientName: "Nadia Bouzid",
    clientPhone: "+33 6 99 88 77 66",
    pickupAddress: "République, Paris",
    dropAddress: "Vincennes, Château",
    type: "IMMEDIATE",
    scheduledAt: null,
    status: "COMPLETED",
    telegramMsgId: null,
    notes: null,
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(2, 16, 30)),
    operator: { name: "Marie Opératrice" },
    acceptance: {
      driver: { name: "Luc Moreau", phone: "+33 6 11 22 33 44" },
      acceptedAt: fmt(daysAgo(2, 16, 33)),
      etaMinutes: null,
      etaUpdatedAt: null,
      notifiedAt: null,
    },
  },
  // Demain
  {
    id: "clx9i",
    clientName: "Thomas Bernard",
    clientPhone: "+33 6 22 33 44 55",
    pickupAddress: "Hôtel Pullman, Paris",
    dropAddress: "Aéroport CDG Terminal 2E",
    type: "SCHEDULED",
    scheduledAt: fmt(daysAhead(1, 6, 0)),
    status: "PENDING",
    telegramMsgId: null,
    notes: "Vol à 8h00 — départ impératif",
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(0, 15, 0)),
    operator: { name: "Marie Opératrice" },
    acceptance: null,
  },
  {
    id: "clx10j",
    clientName: "Emilie Garnier",
    clientPhone: "+33 6 66 77 88 99",
    pickupAddress: "Gare du Nord",
    dropAddress: "Roissy-en-France",
    type: "SCHEDULED",
    scheduledAt: fmt(daysAhead(1, 11, 0)),
    status: "ACCEPTED",
    telegramMsgId: null,
    notes: null,
    distanceText: null,
    durationText: null,
    estimatedPrice: null,
    vehicleType: "VOITURE",
    clientEmail: null,
    invoiceSentAt: null,
    createdAt: fmt(daysAgo(0, 14, 0)),
    operator: { name: "Marie Opératrice" },
    acceptance: {
      driver: { name: "Karim Benali", phone: "+33 6 98 76 54 32" },
      acceptedAt: fmt(daysAgo(0, 14, 15)),
      etaMinutes: null,
      etaUpdatedAt: null,
      notifiedAt: null,
    },
  },
];
